export enum WalletType {
  Cosmostation = 'cosmostation',
  Keplr = 'keplr',
  Leap = 'leap',
  CosmostationMobile = 'cosmostation_mobile',
  KeplrMobile = 'keplr_mobile',
  LeapMobile = 'leap_mobile',
}
export enum GeneralIconType {
  Coreum = 'coreum',
  Network = 'network',
  CheckMark = 'check_mark',
  Info = 'info',
  Error = 'error',
  Close = 'close',
  Percentage = 'percentage',
  ArrowRight = 'arrow_right',
  Copy = 'copy',
  Switch = 'switch',
  Explorer = 'explorer',
  Disconnect = 'disconnect',
  DefaultToken = 'default_token',
  Dots = 'dots',
  Send = 'send',
  Burn = 'burn',
  Manage = 'manage',
  Warning = 'warning',
  AlertClose = 'alert_close',
  Hand = 'hand',
  Mint = 'mint',
  View = 'view',
  Freeze = 'freeze',
  Unfreeze = 'unfreeze',
  Whitelist = 'whitelist',
  File = 'file',
  Edit = 'edit',
};
