/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  data?: Binary | null;
  description?: string | null;
  features?: number[] | null;
  name: string;
  royalty_rate?: string | null;
  symbol: string;
  uri?: string | null;
  uri_hash?: string | null;
}
export type ExecuteMsg = {
  mint_mutable: {
    data?: Binary | null;
    id: string;
    recipient?: string | null;
    uri?: string | null;
    uri_hash?: string | null;
  };
} | {
  mint_immutable: {
    data?: Binary | null;
    id: string;
    recipient?: string | null;
    uri?: string | null;
    uri_hash?: string | null;
  };
} | {
  modify_data: {
    data: Binary;
    id: string;
  };
};
export type QueryMsg = {
  params: {};
} | {
  class: {};
} | {
  classes: {
    issuer: string;
  };
} | {
  balance: {
    owner: string;
  };
} | {
  owner: {
    id: string;
  };
} | {
  supply: {};
} | {
  nft: {
    id: string;
  };
} | {
  nfts: {
    owner?: string | null;
  };
} | {
  class_nft: {};
} | {
  classes_nft: {};
};
export interface BalanceResponse {
  amount: number;
  [k: string]: unknown;
}
export interface ClassResponse {
  class: Class;
  [k: string]: unknown;
}
export interface Class {
  data?: Binary | null;
  description?: string | null;
  id: string;
  name?: string | null;
  symbol?: string | null;
  uri?: string | null;
  uri_hash?: string | null;
  [k: string]: unknown;
}
export interface ClassesResponse {
  classes: Class[];
  pagination: PageResponse;
  [k: string]: unknown;
}
export interface PageResponse {
  next_key?: string | null;
  total?: number | null;
  [k: string]: unknown;
}
export interface NFTResponse {
  nft: NFT;
  [k: string]: unknown;
}
export interface NFT {
  class_id: string;
  data?: Binary | null;
  id: string;
  uri?: string | null;
  uri_hash?: string | null;
  [k: string]: unknown;
}
export interface NFTsResponse {
  nfts: NFT[];
  pagination: PageResponse;
  [k: string]: unknown;
}
export interface OwnerResponse {
  owner: string;
  [k: string]: unknown;
}
export type Uint128 = string;
export interface ParamsResponse {
  params: Params;
  [k: string]: unknown;
}
export interface Params {
  mint_fee: Coin;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface SupplyResponse {
  amount: number;
  [k: string]: unknown;
}